### ISSUE TITLE
Training Topics

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/training#1]
Please post or  +1 topics you'd like to see in the upcoming training!

The goal of the training is to teach everyone how to be effective technically with DoneJS.  As most people are very familiar with most of CanJS's API and the basics of new Steal, this training will emphasize:
- New features
- Advanced features
- Elegant solutions to difficult use cases
- How libraries/modules work

Please submit topic ideas!  The best topics will come from your real-world experience.  Think about the app you've wrote.  Was there a difficult part?  Did you come up with a cool pattern?  Let us know and we'll create a training out of it.
## Submit a topic

Please **_bold and italicize**_ all topics you suggest and include an optional outline or description like:

**_How stache works**_
1. The different parts of stache
2. can/view/parser
3. can/view/target
4. can/view/live
5. can/view/node_list
6. can/view/stache
7. putting it together

Another example:

**_Make Model Year Recipe**_

Go over how to build:

<img width="272" alt="canjs_-_define" src="https://cloud.githubusercontent.com/assets/78602/8769789/a7f3720e-2e6a-11e5-9680-eeb68be8885c.png">
## Upvoting

If you want to upvote, simply add a +1 before the _italic_ topic name:

+1 _Creating a widget that draws more items as they are scrolled into view_

**Comment by kylegifford** [comment]
**_How to manage app state between sub-components on a page**_
Go over best strategies for maintaining app state, especially between child sub-components of the page (which may or may not be used on the same template).

For example, we have an app with several filters for dates, data types, etc:
![screenshot 2015-07-20 08 51 50](https://cloud.githubusercontent.com/assets/4341379/8777275/b29f757a-2ebc-11e5-9b27-b5e4a696722f.png)

and depending on the values of these, graphs and other sections on the page need to fetch updated data and display it.

**Comment by kylegifford** [comment]
**_How to migrate an application to DoneJS**_
Go over strategies for migrating applications built using older versions of CanJS/JavascriptMVC to DoneJS. Possible topics:
1. How do you decide if it's worth migrating?
2. What pieces are best to migrate first?
3. Biggest pitfalls

**Comment by mickmcgrath13** [comment]
+1 _How to manage app state between sub-components on a page_

**Comment by matthewp** [comment]
**_How can-set works**_
I'd like to better understand how can-connect's "data-combine-requests" behavior works in relation to the set algebra provided by can.set in order to understand where it's appropriate to use within apps.

**Comment by mjstahl** [comment]
+1 How to manage app state between sub-components on a page

**Comment by akagomez** [comment]
##### _How to interface can.route with application level components_

| HTTP Request | `can.route.attr()` | Components |
| --- | --- | --- |
| GET /auth/signup | ? | `<app-auth>`, `<app-signup>` |
| GET /auth/login | ? | `<app-auth>`, `<app-login>` |
| GET /user | ? | `<app-user>`, `<app-profile>` |
| GET /user/posts | ? | `<app-user>`, `<app-posts>`, `<app-post>` |
| GET /posts | ? | `<app-posts>`, `<app-post>` |
| GET /posts/new | ? | `<app-posts>`, `<app-post-edit>`(?) |
| GET /search | ? | `<app-search>`, `<app-posts>`, `<app-post>` |

**Comment by akagomez** [comment]
##### _How to implement an edit-in-place interface with CanJS_

Example: http://davehauenstein.com/code/jquery-edit-in-place/example/

**Comment by akagomez** [comment]
##### _How can.view.live handles batched events_
- When to use batching
- When not to use batching
- How to handle batched events

**Comment by marshallswain** [comment]
**Using can-connect**

I realize there's a great documentation site for this, but I would love it if we could dedicate some time to it.

**Comment by julia-allyce** [comment]
**ES6 New Features and Syntax**
Would be nice to cover new features and syntax for ES6: generators, =>, import/export, object literal improvements, etc, etc :smile:

**Comment by mickmcgrath13** [comment]
**_can.Component & JS DOM animations**_
What are the best strategies for animating DOM elements within a Component using javascript, and how best to listen to events related to those animations (triggering dom events vs. updating viewModel and listening to its events vs ..?)

Also, I know that can-animate is in the works;  Should we gear our efforts toward that to accomplish animating elements within a component?  If so, insight into how to best work on a not-yet complete plugin would be good.

**Comment by marshallswain** [comment]
+1. can.Component & JS DOM animations

**Comment by alexisabril** [comment]
**Displaying custom values in a template**
If you have an object such as: `{ cost: 10 }`, perhaps you would want it represented in the view as `$10.00`. This is easy enough with a getter or a helper, however if you want to do arithmetic on this value you'll need the original `10` to manipulate. This is exaggerated further with `can-value`.

```
<input can-value="cost"/>
```

Display should be `$10.00`, however if the user sets the property to `$11.00` or `11`, we should only set `cost` to `11`.

This opens the door for globalization helpers as well. The solution I've used currently for this is creating a custom `can-value`; `can-currency-value` for example. Original reference issue(with a terrible solution): https://github.com/bitovi/canjs/issues/1188

**Comment by mjstahl** [comment]
+1 Displaying custom values in a template

**Comment by DesignByOnyx** [comment]
**checklist for migrating requirejs project to stealjs**
Folder structures (modlets), config settings, build setup, etc.

``` javascript
// original
define(["jquery", "js/control/page"], function ($, Page) { ... });
// 1 to 1 conversion to steal
steal("jquery", "js/control/page.js", function ($, Page) { ... });
// convert `page` to modlet
steal("jquery", "js/control/page", function ($, Page) { ... });
```

**Comment by akagomez** [comment]
##### The order that properties are set on the scope of components

```
foo: { value: 1}
foo { Value: Number }
foo: { set: function () { ... }}
foo: { get: function () { ... }}
<my-component foo="..."></my-component>
```

**Comment by justinbmeyer** [comment]
@akagomez what does that mean?  A `get` doesn't have much with something being `set`?  Default values are not set if something overwrites them.

But mostly, one should consider it indeterminate.  There's not a prescribed order.  Instead, I'd rather talk about the use case where this sorta thing might matter.  What are you doing that it does?

**Comment by matthewp** [comment]
@justinbmeyer one example that often comes up is needing the value of property B inside property A's value function.

**Comment by justinbmeyer** [comment]
@matthewp can you give me a real-world example?  With computes/getters, most of the time .. isn't it ok if the value is defined later?

**Comment by akagomez** [comment]
>  Instead, I'd rather talk about the use case where this sorta thing might matter. What are you doing that it does?

@justinbmeyer Ignore me. I was probably frustrated with myself and looking for excuses. 

With a fresh head this morning I was able to achieve my goal: http://jsbin.com/wawege/edit?html,js,output

**Comment by jeroencornelissen** [comment]
**can-define behaviours**

When defining a DefineMap/List what do we need to use and how do we use it?
The difference between Type/type/Value/value is very confusing.

This is how we define a DefineMap typically (setting a default value for every property).

```
import DefineMap from 'can-define/map/map';

export default DefineMap.extend({
	children : {
		value : []
	},
	hasChildren : {
		value : false
	},
	classes : {
		value : ''
	},
	path : {
		value : null
	}
});

```

**Comment by justinbmeyer** [comment]
@jeroencornelissen you shouldn't have `value: ObjectType`  pretty much ever.  Like `value: []` or `value: {}` or `value: new Something()` ... that value will be shared across all instances of the type. 


In short, `type` and `Type` convert a value during `set` to a specific type.  `type` and `Type` happen before the `set` behavior.  `value` and `Value` are used to initialize the property to a value.

The difference between `Capital` and `lowercase` is that `Capital` behaviors are provided a constructor function and `lowercase` behaviors are provided a function whose return value will be used.  

In general, I often provide a `type`, more rarely a `value`

**Comment by justinbmeyer** [comment]
I'm closing this issue because new topics should be created in another issue.  @jeroencornelissen can you copy your comment into a new issue?
