### ISSUE TITLE
New Hire Training

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/training#27]
- Bitballs (Chris, Bianca)
  - Player Stats: https://github.com/donejs/bitballs/issues/286 (add links to game)
  - Stats for games
- Bitcentive (Joel, Austin) - https://github.com/donejs/bitcentive/issues/281
  - Payouts rewrite + point decay
  - Dollar / points https://github.com/donejs/bitcentive/issues/313, https://github.com/donejs/bitcentive/issues/315
  - Column tooltips
- Landscaper (Chris, Mike)
   - Job Summary Component - https://github.com/bitovi/landscaper-ui/issues/7
   - Add Repo Component - https://github.com/bitovi/landscaper-ui/issues/6
   - Mods Component - https://github.com/bitovi/landscaper-ui/issues/5

**Comment by leoj3n** [comment]
Today we (Austin and I) got done the display of the "Dollars per Point" in the UI.
