### ISSUE TITLE
Keeping Documentation Current

### ISSUE THREAD

**Issue by Macrofig** [bitovi/training#4]
DocumentJS helps keep documentation fairly current but it's not 100% coverage. How does everyone keep documentation up to date? I don't think manually checking code or demos against the docs is the best way to do this, so I'm thinking of something automated.

Similar to test coverage, is there a way to have "documentation coverage"? Things like that.

**Comment by justinbmeyer** [comment]
Is this a feature idea? If yes, it should go in a documentjs issue. We can't really do a training on something that doesn't exist.

**Comment by Macrofig** [comment]
Hah, good point!
